intents:
- greet
- weather_request
- reminder_set
- fine_ask
- fine_normal
- inform
- bye
- thanks
- fine_ask_positive
- fine_ask_negative
- fine_normal_positive
- negative
- affirmative
- fine_normal_negative
entities:
- weather_arg
- time
- number
- amount-of-money
- distance
- location
- reminder
slots:
  amount-of-money:
    type: list
  distance:
    type: list
  location:
    type: text
  number:
    type: list
  reminder:
    type: text
  time:
    type: list
  weather_arg:
    type: list
templates:
  utter_reminder_set:
  - text: Reminder set. Anything else?
  - text: Reminder has been set.
  utter_reminder_noReminder:
  - text: What would your reminder be?
  - text: Ok, whats the reminder about?
  utter_reminder_noTime:
  - text: When will your reminder be?
  - text: When?
  utter_greet:
  - text: Hey, how are you?
  - text: Hello, How are you doing?
  utter_reply:
  - text: I'm doing great. Please let me know what I can do for you.
  - text: I'm doing great. Tell me How can I help you today?
  utter_help:
  - text: Great. How can I help you?
  - text: Great. Tell me How can I help you?
  utter_anything_else:
  - text: No worries. Is there anything else I can help you with?
  - text: No worries. Let me know if there is anything else I can help you with
  utter_bye:
  - text: Bye and have a nice day
  - text: Bbye and have a nice day
  utter_default:
  - text: I am not sure what you're aiming for
  - text: I am sorry but I am not able to get you.
  - text: My appologies but I am not able to get you
  utter_unclear:
  - text: Sorry I did not understand
  - text: What did you mean?
actions:
- action_restart
- action_weather_return
- action_reminder_set
- utter_reminder_set
- utter_reminder_noReminder
- utter_reminder_noTime
- utter_greet
- utter_reply
- utter_help
- utter_anything_else
- utter_bye
- utter_default
- utter_unclear
