language: "en"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "DucklingHTTPExtractor"
  url: "http://0.0.0.0:8000"
  timezone: "UTC"
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor" #BILOU_flag: true if more than 100 examples per entity
  features: [
              ["low", "title", "upper"],
              ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3",
               "suffix2", "upper", "title", "digit", "pattern"],
              ["low", "title", "upper"]
            ]
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"