language: "en"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "DucklingHTTPExtractor"
  url: "http://0.0.0.0:8000"
  timezone: "UTC"
- name: "CRFEntityExtractor" #BILOU_flag: true if more than 100 examples per entity
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"