slots:
  weather_arg:
    type: list
  time:
    type: list
  number:
    type: list
  amount-of-money:
    type: list
  distance:
    type: list

entities:
- weather_arg
- time
- number
- amount-of-money
- distance

intents:
- greet
- goodbye
- mood_affirm
- mood_deny
- mood_great
- mood_unhappy
- weather_request
- reminder_set_intent
- reminder_set_noIntent

actions:
- action_restart
- action_weather_return
- utter_reminder_intent
- utter_reminder_noIntent
- utter_greet
- utter_reply
- utter_help
- utter_anything_else
- utter_bye
- utter_default
- utter_unclear

templates:
  utter_reminder_intent:
    - text: Reminder set. Anything else?
    - text: Reminder has been set.
  utter_reminder_noIntent:
    - text: What would your reminder be?
    - text: Ok, whats the reminder about?
  utter_greet:
    - text: Hey, how are you?
    - text: Hello, How are you doing?
  utter_reply:
    - text: I'm doing great. Please let me know what I can do for you.
    - text: I'm doing great. Tell me How can I help you today?
  utter_help:
    - text: Great. How can I help you?
    - text: Great. Tell me How can I help you?
    - text: Great. Tell me what all news you would like to get.
  utter_anything_else:
    - text: No worries. Is there anything else I can help you with?
    - text: No worries. Let me know if there is anything else I can help you with
  utter_bye:
    - text: Bye and have a nice day
    - text: Bbye and have a nice day
  utter_default:
    - text: I am not sure what you're aiming for
    - text: I am sorry but I am not able to get you.
    - text: My appologies but I am not able to get you